#!/bin/sh
# This file is auto-generated by make-keys.sh
# please re-run make-keys.sh to update it
useradd base
usermod -aG rpm_uploaders base
mkdir -p repo/files/home/base/.ssh
chown -R base:base repo/files/home/base/
useradd cgal
usermod -aG rpm_uploaders cgal
mkdir -p repo/files/home/cgal/.ssh
chown -R cgal:cgal repo/files/home/cgal/
useradd flightgear
usermod -aG rpm_uploaders flightgear
mkdir -p repo/files/home/flightgear/.ssh
chown -R flightgear:flightgear repo/files/home/flightgear/
useradd flightgear-data
usermod -aG rpm_uploaders flightgear-data
mkdir -p repo/files/home/flightgear-data/.ssh
chown -R flightgear-data:flightgear-data repo/files/home/flightgear-data/
useradd gdal
usermod -aG rpm_uploaders gdal
mkdir -p repo/files/home/gdal/.ssh
chown -R gdal:gdal repo/files/home/gdal/
useradd openscenegraph
usermod -aG rpm_uploaders openscenegraph
mkdir -p repo/files/home/openscenegraph/.ssh
chown -R openscenegraph:openscenegraph repo/files/home/openscenegraph/
useradd repo
usermod -aG rpm_uploaders repo
mkdir -p repo/files/home/repo/.ssh
chown -R repo:repo repo/files/home/repo/
useradd simgear
usermod -aG rpm_uploaders simgear
mkdir -p repo/files/home/simgear/.ssh
chown -R simgear:simgear repo/files/home/simgear/
useradd ssh
usermod -aG rpm_uploaders ssh
mkdir -p repo/files/home/ssh/.ssh
chown -R ssh:ssh repo/files/home/ssh/
useradd terragear
usermod -aG rpm_uploaders terragear
mkdir -p repo/files/home/terragear/.ssh
chown -R terragear:terragear repo/files/home/terragear/
