#!/bin/sh
# keys required to get the packages uploaded to the repo with fewer errors
# make the key available to the repo container
mkdir -p repo/files/root/
echo "#!/bin/sh" > repo/files/root/addusers.sh
echo "# This file is auto-generated by make-keys.sh" >> repo/files/root/addusers.sh
echo "# please re-run make-keys.sh to update it" >> repo/files/root/addusers.sh
# make the key available to the package containers
for rpm in $( ls -d */ | sed 's/\/$//'); do
  rm -rf $rpm/ssh
  mkdir -p $rpm/ssh
  ssh-keygen -f $rpm/ssh/id_rsa -P ""
  mkdir -p repo/files/home/$rpm/.ssh
  cp $rpm/ssh/id_rsa.pub repo/files/home/$rpm/.ssh/authorized_keys
  echo useradd $rpm >> repo/files/root/addusers.sh
  echo usermod -aG rpm_uploaders $rpm >> repo/files/root/addusers.sh
  echo mkdir -p repo/files/home/$rpm/.ssh >> repo/files/root/addusers.sh
  echo chown -R $rpm:$rpm repo/files/home/$rpm/ >> repo/files/root/addusers.sh
done

# after all the keys are generated, enable the repo to be trusted
for rpm in $( ls -d */ | sed 's/\/$//'); do
  rm -f $rpm/ssh/known_hosts
  cp repo/ssh/id_rsa.pub $rpm/ssh/known_hosts
  sed 's/^/repo.rpm\ /' $rpm/ssh/known_hosts -i
done

